# Generated by Django 4.2.2 on 2023-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('CD', 'CARDIOLOGY'), ('DG', 'DIAGNOSIS'), ('SG', 'SURGERY'), ('FA', 'FIRST AID'), ('IC', 'INTENSIVE CARE'), ('GC', 'GYNAECOLOGY'), ('NS', 'NURSING'), ('PM', 'PHARMACY'), ('DL', 'DIALYSIS'), ('OP', 'ORTHOPAEDICS')], max_length=15)),
                ('image', models.ImageField(upload_to='service_image')),
                ('description', models.TextField()),
            ],
        ),
    ]
