# Generated by Django 4.2.2 on 2023-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='service',
            field=models.CharField(choices=[('CARDIOLOGY', 'CARDIOLOGY'), ('DIAGNOSIS', 'DIAGNOSIS'), ('SURGERY', 'SURGERY'), ('FIRST AID', 'FIRST AID'), ('INTENSIVE CARE', 'INTENSIVE CARE'), ('GYNAECOLOGY', 'GYNAECOLOGY'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('DIALYSIS', 'DIALYSIS'), ('ORTHOPAEDICS', 'ORTHOPAEDICS')], max_length=25),
        ),
    ]
