# Generated by Django 4.2.2 on 2023-06-17 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=15)),
                ('sickness_type', models.CharField(max_length=20)),
                ('sickness_description', models.TextField()),
                ('health_status', models.CharField(choices=[('S', 'Sick'), ('R', 'Recovering'), ('H', 'Healthy')], max_length=15)),
                ('height', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='patient_image')),
                ('address', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
