# Generated by Django 4.2.2 on 2023-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_status',
            field=models.CharField(blank=True, choices=[('S', 'Sick'), ('R', 'Recovering'), ('H', 'Healthy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, upload_to='patient_image'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sickness_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sickness_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single')], max_length=15),
        ),
    ]
