# Generated by Django 4.2.2 on 2023-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_status',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Recovering', 'Recovering'), ('Healthy', 'Healthy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], max_length=15),
        ),
    ]
