# Generated by Django 4.2.2 on 2023-06-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_patient_gender_alter_patient_health_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
                ('date_requested', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.doctor')),
            ],
        ),
    ]
