# Generated by Django 4.2.2 on 2023-06-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='full_name',
        ),
    ]
