# Generated by Django 4.2.2 on 2023-07-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_patient_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_joined']},
        ),
    ]
