# Generated by Django 4.0.3 on 2023-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='patient_image'),
        ),
    ]
